#!/bin/bash

set -ex

log_file=".install.log.$(date +%Y%m%d%H%M%S)"
exec &> >(tee -a "$log_file")

lab=adalab
loc="westus"

az account show | grep -q Enabled

[ -d .ssh ] && rm -rf .ssh
mkdir .ssh && ssh-keygen -t rsa -q -f .ssh/az_acs -N ''
cat azuredeploy.parameters.json | sed -e "s/SSHKEYHERE/$(cat .ssh/az_acs.pub|sed -e 's/\//\\\//g' -e 's/+/\\+/g')/" >.template-azuredeploy.parameters.json

echo "$(date +%Y%m%d%H%M%S) Deploying $lab in $loc"

cat .template-azuredeploy.parameters.json | sed -e "s/FIXME/$lab/" >.$lab-azuredeploy.parameters.json

az group create -n $lab -l $loc
az group deployment create -g $lab --template-uri "https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-acs-kubernetes/azuredeploy.json" --parameters @.$lab-azuredeploy.parameters.json && rm -f .$lab-azuredeploy.parameters.json &

wait

rm -f .template-azuredeploy.parameters.json

ansible '~containerservice-adalab' -m ping
ansible-playbook install.yaml

